### PR TITLE
LMS linker

### PR DESCRIPTION
**Pull request by Tantalus13A98B5F**

### CODE REVIEW

**Comment by Tantalus13A98B5F** [comment]
## Changes

1. `hardTopFun` is changed to use `λ` instead of `top-λ`.
2. The transformer in Driver.scala has to be disabled, to stop DCE from eliminating everything.
3. In CPSEngine.scala, `hardTopFun` is used instead of `topFun`.

## Observations

1. Both External.scala and Driver.scala can only generate one function in the library.
2. External.scala generates the last function (`__errno_location`), while Driver.scala generates the first function (`preHeapGen`)

## Guesses

1. Effects on a `λ` node do not matter to the scheduling, while effects on a block do matter.
2. Transformer will not retain effects on `λ` nodes when re-generating the graph.

**Comment by Kraks** [comment]
> The transformer in Driver.scala has to be disabled, to stop DCE from eliminating everything.

Do we also lose these optimizations when compiling libraries?

**Comment by Tantalus13A98B5F** [comment]
This is just a (not working) draft for now. That solely means we have to fix the transformer behavior before we can actually use it for production.

**Comment by Tantalus13A98B5F** [comment]
## To Dos

- [ ] Find out how to set effects on block to make use of `scheduleBlock`. This should be intuitive, however I can't see why `preHeapGen` is the one generated.
- [ ] Tweak transformer to retain effects on lambda nodes.

**Comment by Tantalus13A98B5F** [comment]
- [ ] noop handling for libc_llsc_posix
- [ ] name mangling for `app_main`
- [ ] generate branchmap for application by extending the given `cov()` from the library

**Comment by Tantalus13A98B5F** [comment]
# Test Instructions

1. Check out this branch, pull the latest code.
2. Go grab `/scratch1/jia137/GenSym-wip/llsc_gen/lmslinker.tar.gz` and unzip into your `llsc_gen` folder
3. The following `java -version` is preferred for best serialization compatibility.

    ```
    openjdk version "1.8.0_292"
    OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
    ```

4. Run the following in SBT to compile an application without linking it first. Change the part in `<...>` as you wish.

    ```
    runMain sai.llsc.RunLLSC --engine=app --lib=./llsc_gen/libc_<klee>_posix --use-argv --main-opt=O3 <../echo.ll>
    ```

5. Compile & run the application like before.

**Pull request merged**
